/**
 * Sajilo Nepali - Massive Vocabulary Database
 * Tailored for German learners with English translations.
 */

const vocabularyList = [
    // --- 1. ESSENTIALS & GREETINGS ---
    { nepali: "Namaste", english: "Hello / I bow to you", german: "Hallo / Grüße", category: "Essentials" },
    { nepali: "Dhanyabaad", english: "Thank you", german: "Danke", category: "Essentials" },
    { nepali: "Sanchai hunuchha?", english: "How are you?", german: "Wie geht es dir?", category: "Essentials" },
    { nepali: "Ma sanchai chhu", english: "I am fine", german: "Mir geht es gut", category: "Essentials" },
    { nepali: "Hajur", english: "Yes (polite) / Excuse me?", german: "Ja (höflich) / Wie bitte?", category: "Essentials" },
    { nepali: "Hoina", english: "No", german: "Nein", category: "Essentials" },
    { nepali: "Kripaya", english: "Please", german: "Bitte", category: "Essentials" },
    { nepali: "Maaf garnuhos", english: "I am sorry / Excuse me", german: "Es tut mir leid / Entschuldigung", category: "Essentials" },
    { nepali: "Pheri bhetaula", english: "See you again", german: "Auf Wiedersehen", category: "Essentials" },
    { nepali: "Tapaiko naam ke ho?", english: "What is your name?", german: "Wie heißt du?", category: "Essentials" },
    { nepali: "Mero naam... ho", english: "My name is...", german: "Mein Name ist...", category: "Essentials" },
    { nepali: "Subha prabhat", english: "Good morning", german: "Guten Morgen", category: "Essentials" },
    { nepali: "Subha raatri", english: "Good night", german: "Gute Nacht", category: "Essentials" },
    { nepali: "Thik chha", english: "It's okay / All right", german: "In Ordnung / Alles klar", category: "Essentials" },

    // --- 2. ROMANCE & AFFECTION (Specially for Luna) ---
    { nepali: "Luna, ma timilai maya garchhu", english: "Luna, I love you", german: "Luna, ich liebe dich", category: "Romance" },
    { nepali: "Mero pyaari Luna", english: "My beloved Luna", german: "Meine geliebte Luna", category: "Romance" },
    { nepali: "Timi mero sabai thok hau", english: "You are my everything", german: "Du bist mein Alles", category: "Romance" },
    { nepali: "Mero mutu ko tukra", english: "Piece of my heart", german: "Ein Stück meines Herzens", category: "Romance" },
    { nepali: "Maya ko poko", english: "Bundle of love", german: "Mein Bündel voller Liebe", category: "Romance" },
    { nepali: "Mutu ko dhadkan", english: "My heartbeat", german: "Mein Herzschlag", category: "Romance" },
    { nepali: "Mero pyaaro manxea", english: "My lovely person / My dear", german: "Mein lieber Mensch / Mein Schatz", category: "Romance" },
    { nepali: "Mero sansar", english: "My world", german: "Meine Welt", category: "Romance" },
    { nepali: "Timi bina ma bachna sakdina", english: "I can't live without you", german: "Ich kann ohne dich nicht leben", category: "Romance" },
    { nepali: "Jindagi vari saath diula", english: "I will be with you for a lifetime", german: "Ich werde ein Leben lang bei dir sein", category: "Romance" },
    { nepali: "Mero mutu", english: "My heart", german: "Mein Herz", category: "Romance" },
    { nepali: "Timi dherai ramri chhau", english: "You are very beautiful", german: "Du bist sehr schön", category: "Romance" },
    { nepali: "Malaai timro yaad aayo", english: "I miss you", german: "Ich vermisse dich", category: "Romance" },
    { nepali: "Timi mero jivan hau", english: "You are my life", german: "Du bist mein Leben", category: "Romance" },
    { nepali: "Angaalo", english: "Hug", german: "Umarmung", category: "Romance" },
    { nepali: "Chumma", english: "Kiss", german: "Kuss", category: "Romance" },
    { nepali: "Mero maya", english: "My love", german: "Meine Liebe", category: "Romance" },
    { nepali: "Timro aakha haru ramro chhan", english: "Your eyes are beautiful", german: "Deine Augen sind wunderschön", category: "Romance" },

    // --- 3. TREKKING & NATURE ---
    { nepali: "Himal", english: "Mountain", german: "Berg / Himalaya", category: "Trekking" },
    { nepali: "Bato", english: "Trail / Path", german: "Weg / Pfad", category: "Trekking" },
    { nepali: "Ukalo", english: "Uphill", german: "Bergauf", category: "Trekking" },
    { nepali: "Oralo", english: "Downhill", german: "Bergab", category: "Trekking" },
    { nepali: "Bhanjyang", english: "Mountain Pass", german: "Gebirgspass", category: "Trekking" },
    { nepali: "Jungle", english: "Forest / Jungle", german: "Wald / Dschungel", category: "Trekking" },
    { nepali: "Nadi", english: "River", german: "Fluss", category: "Trekking" },
    { nepali: "Jharana", english: "Waterfall", german: "Wasserfall", category: "Trekking" },
    { nepali: "Mausam", english: "Weather", german: "Wetter", category: "Trekking" },
    { nepali: "Gham laagyo", english: "It is sunny", german: "Es ist sonnig", category: "Trekking" },
    { nepali: "Paani parchha?", english: "Will it rain?", german: "Wird es regnen?", category: "Trekking" },
    { nepali: "Hami thakyaung", english: "We are tired", german: "Wir sind müde", category: "Trekking" },
    { nepali: "Bistarai", english: "Slowly", german: "Langsam", category: "Trekking" },
    { nepali: "Gau", english: "Village", german: "Dorf", category: "Trekking" },

    // --- 4. FOOD & DINING ---
    { nepali: "Khaanaa", english: "Food / Meal", german: "Essen", category: "Food" },
    { nepali: "Paani", english: "Water", german: "Wasser", category: "Food" },
    { nepali: "Chiyaa", english: "Tea", german: "Tee", category: "Food" },
    { nepali: "Mitho chha", english: "It is delicious", german: "Es ist lecker", category: "Food" },
    { nepali: "Piro", english: "Spicy", german: "Scharf", category: "Food" },
    { nepali: "Malaai bhok laagyo", english: "I am hungry", german: "Ich habe Hunger", category: "Food" },
    { nepali: "Malaai tirkha laagyo", english: "I am thirsty", german: "Ich habe Durst", category: "Food" },
    { nepali: "Dal Bhat", english: "Lentils and Rice", german: "Linsen und Reis", category: "Food" },
    { nepali: "Tarkaari", english: "Vegetables", german: "Gemüse", category: "Food" },
    { nepali: "Maasu", english: "Meat", german: "Fleisch", category: "Food" },
    { nepali: "Kukhuraako maasu", english: "Chicken", german: "Hähnchen", category: "Food" },
    { nepali: "Achar", english: "Pickle", german: "Eingelegtes (Pickle)", category: "Food" },
    { nepali: "Nun", english: "Salt", german: "Salz", category: "Food" },
    { nepali: "Chini", english: "Sugar", german: "Zucker", category: "Food" },
    { nepali: "Dahi", english: "Yogurt", german: "Joghurt", category: "Food" },

    // --- 5. NUMBERS & SHOPPING ---
    { nepali: "Kati ho?", english: "How much?", german: "Wie viel?", category: "Shopping" },
    { nepali: "Paisa", english: "Money", german: "Geld", category: "Shopping" },
    { nepali: "Mahango", english: "Expensive", german: "Teuer", category: "Shopping" },
    { nepali: "Sasto", english: "Cheap", german: "Billig", category: "Shopping" },
    { nepali: "Ali milauhos", english: "Please discount a bit", german: "Bitte geben Sie einen Rabatt", category: "Shopping" },
    { nepali: "Ek", english: "One", german: "Eins", category: "Numbers" },
    { nepali: "Dui", english: "Two", german: "Zwei", category: "Numbers" },
    { nepali: "Teen", english: "Three", german: "Drei", category: "Numbers" },
    { nepali: "Chaar", english: "Four", german: "Vier", category: "Numbers" },
    { nepali: "Paanch", english: "Five", german: "Fünf", category: "Numbers" },
    { nepali: "Chha", english: "Six", german: "Sechs", category: "Numbers" },
    { nepali: "Saat", english: "Seven", german: "Sieben", category: "Numbers" },
    { nepali: "Aath", english: "Eight", german: "Acht", category: "Numbers" },
    { nepali: "Nau", english: "Nine", german: "Neun", category: "Numbers" },
    { nepali: "Das", english: "Ten", german: "Zehn", category: "Numbers" },
    { nepali: "Say", english: "One Hundred", german: "Hundert", category: "Numbers" },
    { nepali: "Hazaar", english: "One Thousand", german: "Tausend", category: "Numbers" },

    // --- 6. EMERGENCY & HEALTH ---
    { nepali: "Guhaar!", english: "Help!", german: "Hilfe!", category: "Emergency" },
    { nepali: "Aspatal", english: "Hospital", german: "Krankenhaus", category: "Emergency" },
    { nepali: "Doctor", english: "Doctor", german: "Arzt", category: "Emergency" },
    { nepali: "Aushadhi", english: "Medicine", german: "Medizin", category: "Emergency" },
    { nepali: "Mero tauko dukhyo", english: "My head hurts", german: "Mein Kopf tut weh", category: "Emergency" },
    { nepali: "Ma birami chhu", english: "I am sick", german: "Ich bin krank", category: "Emergency" },
    { nepali: "Prahari", english: "Police", german: "Polizei", category: "Emergency" },
    { nepali: "Ma haraye", english: "I am lost", german: "Ich bin verloren", category: "Emergency" },
    { nepali: "Surakshit", english: "Safe", german: "Sicher", category: "Emergency" },

    // --- 7. COMMON VERBS (To Do things) ---
    { nepali: "Khaanu", english: "To eat", german: "Essen (Verb)", category: "Verbs" },
    { nepali: "Pivnu", english: "To drink", german: "Trinken", category: "Verbs" },
    { nepali: "Sutnu", english: "To sleep", german: "Schlafen", category: "Verbs" },
    { nepali: "Jaanu", english: "To go", german: "Gehen", category: "Verbs" },
    { nepali: "Aunu", english: "To come", german: "Kommen", category: "Verbs" },
    { nepali: "Garnu", english: "To do", german: "Machen / Tun", category: "Verbs" },
    { nepali: "Bholnu", english: "To speak", german: "Sprechen", category: "Verbs" },
    { nepali: "Herne", english: "To watch / see", german: "Sehen", category: "Verbs" },
    { nepali: "Kinnu", english: "To buy", german: "Kaufen", category: "Verbs" },
    { nepali: "Dinu", english: "To give", german: "Geben", category: "Verbs" },
    
    // --- 8. TIME & DAYS ---
    { nepali: "Aaja", english: "Today", german: "Heute", category: "Time" },
    { nepali: "Bholi", english: "Tomorrow", german: "Morgen", category: "Time" },
    { nepali: "Hijo", english: "Yesterday", german: "Gestern", category: "Time" },
    { nepali: "Bihana", english: "Morning", german: "Morgen (Tageszeit)", category: "Time" },
    { nepali: "Deuso", english: "Afternoon", german: "Nachmittag", category: "Time" },
    { nepali: "Beluka", english: "Evening", german: "Abend", category: "Time" },
    { nepali: "Raati", english: "Night", german: "Nacht", category: "Time" },
    { nepali: "Samaya", english: "Time", german: "Zeit", category: "Time" },

    // --- 9. ANIMALS (Trekking Wildlife) ---
    { nepali: "Kukur", english: "Dog", german: "Hund", category: "Animals" },
    { nepali: "Biraalo", english: "Cat", german: "Katze", category: "Animals" },
    { nepali: "Gai", english: "Cow", german: "Kuh", category: "Animals" },
    { nepali: "Bakhra", english: "Goat", german: "Ziege", category: "Animals" },
    { nepali: "Balu", english: "Bear", german: "Bär", category: "Animals" },
    { nepali: "Bagh", english: "Tiger", german: "Tiger", category: "Animals" },
    { nepali: "Charra", english: "Bird", german: "Vogel", category: "Animals" },

    // --- 10. COLORS & ADJECTIVES ---
    { nepali: "Rato", english: "Red", german: "Rot", category: "Adjectives" },
    { nepali: "Nilo", english: "Blue", german: "Blau", category: "Adjectives" },
    { nepali: "Hariyo", english: "Green", german: "Grün", category: "Adjectives" },
    { nepali: "Kalo", english: "Black", german: "Schwarz", category: "Adjectives" },
    { nepali: "Seto", english: "White", german: "Weiß", category: "Adjectives" },
    { nepali: "Thulo", english: "Big", german: "Groß", category: "Adjectives" },
    { nepali: "Saano", english: "Small", german: "Klein", category: "Adjectives" },
    { nepali: "Ramro", english: "Good / Nice", german: "Gut / Schön", category: "Adjectives" },
    { nepali: "Naramro", english: "Bad", german: "Schlecht", category: "Adjectives" },
    { nepali: "Tato", english: "Hot (Temp)", german: "Heiß", category: "Adjectives" },
    { nepali: "Chiso", english: "Cold (Temp)", german: "Kalt", category: "Adjectives" }
,
    { nepali: "Aama", english: "Mother", german: "Mutter", category: "Family" },
    { nepali: "Buwa", english: "Father", german: "Vater", category: "Family" },
    { nepali: "Daju", english: "Older Brother", german: "Älterer Bruder", category: "Family" },
    { nepali: "Bhai", english: "Younger Brother", german: "Jüngerer Bruder", category: "Family" },
    { nepali: "Didi", english: "Older Sister", german: "Ältere Schwester", category: "Family" },
    { nepali: "Bahini", english: "Younger Sister", german: "Jüngere Schwester", category: "Family" },
    { nepali: "Hajurba", english: "Grandfather", german: "Großvater", category: "Family" },
    { nepali: "Hajuraama", english: "Grandmother", german: "Großmutter", category: "Family" },
    { nepali: "Chhora", english: "Son", german: "Sohn", category: "Family" },
    { nepali: "Chhori", english: "Daughter", german: "Tochter", category: "Family" },
    { nepali: "Mama", english: "Maternal Uncle", german: "Onkel (mütterlicherseits)", category: "Family" },
    { nepali: "Maiju", english: "Maternal Aunt", german: "Tante (mütterlicherseits)", category: "Family" },
    { nepali: "Kaka", english: "Paternal Uncle", german: "Onkel (väterlicherseits)", category: "Family" },
    { nepali: "Kaki", english: "Paternal Aunt", german: "Tante (väterlicherseits)", category: "Family" },
    { nepali: "Sathi", english: "Friend", german: "Freund", category: "Family" },
    { nepali: "Shreeman", english: "Husband", german: "Ehemann", category: "Family" },
    { nepali: "Shreemati", english: "Wife", german: "Ehefrau", category: "Family" },
    { nepali: "Tauko", english: "Head", german: "Kopf", category: "Body Parts" },
    { nepali: "Kapaal", english: "Hair", german: "Haar", category: "Body Parts" },
    { nepali: "Aakha", english: "Eye", german: "Auge", category: "Body Parts" },
    { nepali: "Naak", english: "Nose", german: "Nase", category: "Body Parts" },
    { nepali: "Mukh", english: "Mouth", german: "Mund", category: "Body Parts" },
    { nepali: "Kaan", english: "Ear", german: "Ohr", category: "Body Parts" },
    { nepali: "Daat", english: "Tooth", german: "Zahn", category: "Body Parts" },
    { nepali: "Jibro", english: "Tongue", german: "Zunge", category: "Body Parts" },
    { nepali: "Ghati", english: "Neck", german: "Hals", category: "Body Parts" },
    { nepali: "Haat", english: "Hand", german: "Hand", category: "Body Parts" },
    { nepali: "Aunla", english: "Finger", german: "Finger", category: "Body Parts" },
    { nepali: "Chhati", english: "Chest", german: "Brust", category: "Body Parts" },
    { nepali: "Pet", english: "Stomach", german: "Magen", category: "Body Parts" },
    { nepali: "Khutta", english: "Leg", german: "Bein", category: "Body Parts" },
    { nepali: "Paitala", english: "Foot", german: "Fuß", category: "Body Parts" },
    { nepali: "Ragat", english: "Blood", german: "Blut", category: "Body Parts" },
    { nepali: "Mutu", english: "Heart (organ)", german: "Herz (Organ)", category: "Body Parts" },
    { nepali: "Ghar", english: "House", german: "Haus", category: "Household" },
    { nepali: "Kotha", english: "Room", german: "Zimmer", category: "Household" },
    { nepali: "Dhoka", english: "Door", german: "Tür", category: "Household" },
    { nepali: "Jhyal", english: "Window", german: "Fenster", category: "Household" },
    { nepali: "Pankha", english: "Fan", german: "Ventilator", category: "Household" },
    { nepali: "Batti", english: "Light / Lamp", german: "Licht / Lampe", category: "Household" },
    { nepali: "Ochhyan", english: "Bed", german: "Bett", category: "Household" },
    { nepali: "Sirani", english: "Pillow", german: "Kissen", category: "Household" },
    { nepali: "Kambal", english: "Blanket", german: "Decke", category: "Household" },
    { nepali: "Mech", english: "Chair", german: "Stuhl", category: "Household" },
    { nepali: "Tebul", english: "Table", german: "Tisch", category: "Household" },
    { nepali: "Bhuin", english: "Floor", german: "Boden", category: "Household" },
    { nepali: "Bhitta", english: "Wall", german: "Wand", category: "Household" },
    { nepali: "Bhanda", english: "Pot / Vessel", german: "Topf / Gefäß", category: "Household" },
    { nepali: "Chamcha", english: "Spoon", german: "Löffel", category: "Household" },
    { nepali: "Kachaura", english: "Bowl", german: "Schüssel", category: "Household" },
    { nepali: "Churi", english: "Knife", german: "Messer", category: "Household" },
    { nepali: "Aago", english: "Fire", german: "Feuer", category: "Household" },
    { nepali: "Luga", english: "Clothes", german: "Kleidung", category: "Clothing" },
    { nepali: "Topi", english: "Hat", german: "Hut", category: "Clothing" },
    { nepali: "Jutta", english: "Shoes", german: "Schuhe", category: "Clothing" },
    { nepali: "Moja", english: "Socks", german: "Socken", category: "Clothing" },
    { nepali: "Chappal", english: "Slippers", german: "Hausschuhe", category: "Clothing" },
    { nepali: "Kamij", english: "Shirt", german: "Hemd", category: "Clothing" },
    { nepali: "Suruwal", english: "Trousers/Pants", german: "Hose", category: "Clothing" },
    { nepali: "Rumaal", english: "Handkerchief", german: "Taschentuch", category: "Clothing" },
    { nepali: "Peti", english: "Belt", german: "Gürtel", category: "Clothing" },
    { nepali: "Chasma", english: "Glasses", german: "Brille", category: "Clothing" },
    { nepali: "Ghari", english: "Watch", german: "Uhr", category: "Clothing" },
    { nepali: "Baagh", english: "Tiger", german: "Tiger", category: "Animals" },
    { nepali: "Bhalu", english: "Bear", german: "Bär", category: "Animals" },
    { nepali: "Haatti", english: "Elephant", german: "Elefant", category: "Animals" },
    { nepali: "Gai", english: "Cow", german: "Kuh", category: "Animals" },
    { nepali: "Bhaisi", english: "Buffalo", german: "Büffel", category: "Animals" },
    { nepali: "Kukur", english: "Dog", german: "Hund", category: "Animals" },
    { nepali: "Biraalo", english: "Cat", german: "Katze", category: "Animals" },
    { nepali: "Bakhra", english: "Goat", german: "Ziege", category: "Animals" },
    { nepali: "Bheda", english: "Sheep", german: "Schaf", category: "Animals" },
    { nepali: "Ghodaa", english: "Horse", german: "Pferd", category: "Animals" },
    { nepali: "Kukhura", english: "Chicken", german: "Huhn", category: "Animals" },
    { nepali: "Chara", english: "Bird", german: "Vogel", category: "Animals" },
    { nepali: "Kag", english: "Crow", german: "Krähe", category: "Animals" },
    { nepali: "Suga", english: "Parrot", german: "Papagei", category: "Animals" },
    { nepali: "Machha", english: "Fish", german: "Fisch", category: "Animals" },
    { nepali: "Bhyaguta", english: "Frog", german: "Frosch", category: "Animals" },
    { nepali: "Sarp", english: "Snake", german: "Schlange", category: "Animals" },
    { nepali: "Kira", english: "Insect", german: "Insekt", category: "Animals" },
    { nepali: "Mausi", english: "Spider", german: "Spinne", category: "Animals" },
    { nepali: "Lammkhutte", english: "Mosquito", german: "Mücke", category: "Animals" },
    { nepali: "Makkhai", english: "Fly", german: "Fliege", category: "Animals" },
    { nepali: "Kamila", english: "Ant", german: "Ameise", category: "Animals" },
    { nepali: "Bandar", english: "Monkey", german: "Affe", category: "Animals" },
    { nepali: "Musa", english: "Mouse", german: "Maus", category: "Animals" },
    { nepali: " खरायो (Kharayo)", english: "Rabbit", german: "Hase", category: "Animals" },
    { nepali: "Bandel", english: "Wild Boar", german: "Wildschwein", category: "Animals" },
    { nepali: "Harin", english: "Deer", german: "Reh", category: "Animals" },
    { nepali: "Kalo", english: "Black", german: "Schwarz", category: "Colors" },
    { nepali: "Seto", english: "White", german: "Weiß", category: "Colors" },
    { nepali: "Rato", english: "Red", german: "Rot", category: "Colors" },
    { nepali: "Nilo", english: "Blue", german: "Blau", category: "Colors" },
    { nepali: "Hariyo", english: "Green", german: "Grün", category: "Colors" },
    { nepali: "Pahelo", english: "Yellow", german: "Gelb", category: "Colors" },
    { nepali: "Suntala", english: "Orange", german: "Orange", category: "Colors" },
    { nepali: "Gulabi", english: "Pink", german: "Rosa", category: "Colors" },
    { nepali: "Khairo", english: "Brown", german: "Braun", category: "Colors" },
    { nepali: "Khaiji", english: "Grey", german: "Grau", category: "Colors" },
    { nepali: "Baingani", english: "Purple", german: "Lila", category: "Colors" },
    { nepali: "Sunaualo", english: "Golden", german: "Golden", category: "Colors" },
    { nepali: "Chandi", english: "Silver", german: "Silber", category: "Colors" },
    { nepali: "Aaile", english: "Now", german: "Jetzt", category: "Time" },
    { nepali: "Pachi", english: "Later", german: "Später", category: "Time" },
    { nepali: "Aaja", english: "Today", german: "Heute", category: "Time" },
    { nepali: "Hijo", english: "Yesterday", german: "Gestern", category: "Time" },
    { nepali: "Bholi", english: "Tomorrow", german: "Morgen", category: "Time" },
    { nepali: "Bihana", english: "Morning", german: "Morgen (Zeit)", category: "Time" },
    { nepali: "Diuso", english: "Afternoon", german: "Nachmittag", category: "Time" },
    { nepali: "Beluka", english: "Evening", german: "Abend", category: "Time" },
    { nepali: "Rati", english: "Night", german: "Nacht", category: "Time" },
    { nepali: "Din", english: "Day", german: "Tag", category: "Time" },
    { nepali: "Hapta", english: "Week", german: "Woche", category: "Time" },
    { nepali: "Mahina", english: "Month", german: "Monat", category: "Time" },
    { nepali: "Barsa", english: "Year", german: "Jahr", category: "Time" },
    { nepali: "Bela", english: "Time / Moment", german: "Zeit / Moment", category: "Time" },
    { nepali: "Ghanta", english: "Hour", german: "Stunde", category: "Time" },
    { nepali: "Minet", english: "Minute", german: "Minute", category: "Time" },
    { nepali: "Sekend", english: "Second", german: "Sekunde", category: "Time" },
    { nepali: "Aitabara", english: "Sunday", german: "Sonntag", category: "Time" },
    { nepali: "Sombaara", english: "Monday", german: "Montag", category: "Time" },
    { nepali: "Mangalbaara", english: "Tuesday", german: "Dienstag", category: "Time" },
    { nepali: "Budhabaara", english: "Wednesday", german: "Mittwoch", category: "Time" },
    { nepali: "Bihibaara", english: "Thursday", german: "Donnerstag", category: "Time" },
    { nepali: "Sukrabaara", english: "Friday", german: "Freitag", category: "Time" },
    { nepali: "Sanibaara", english: "Saturday", german: "Samstag", category: "Time" },
    { nepali: "Khaanu", english: "To eat", german: "Essen (verb)", category: "Verbs" },
    { nepali: "Pinu", english: "To drink", german: "Trinken", category: "Verbs" },
    { nepali: "Sutnu", english: "To sleep", german: "Schlafen", category: "Verbs" },
    { nepali: "Uthnu", english: "To wake up / stand up", german: "Aufwachen / Aufstehen", category: "Verbs" },
    { nepali: "Jaanu", english: "To go", german: "Gehen", category: "Verbs" },
    { nepali: "Aunu", english: "To come", german: "Kommen", category: "Verbs" },
    { nepali: "Kudnu", english: "To run", german: "Rennen", category: "Verbs" },
    { nepali: "Hidnu", english: "To walk", german: "Laufen", category: "Verbs" },
    { nepali: "Garnu", english: "To do", german: "Machen / Tun", category: "Verbs" },
    { nepali: "Bholnu", english: "To speak", german: "Sprechen", category: "Verbs" },
    { nepali: "Bhannu", english: "To say", german: "Sagen", category: "Verbs" },
    { nepali: "Sodnu", english: "To ask", german: "Fragen", category: "Verbs" },
    { nepali: "Sunnu", english: "To listen / hear", german: "Hören", category: "Verbs" },
    { nepali: "Herne", english: "To watch / look", german: "Schauen / Gucken", category: "Verbs" },
    { nepali: "Dekhnu", english: "To see", german: "Sehen", category: "Verbs" },
    { nepali: "Lekhnu", english: "To write", german: "Schreiben", category: "Verbs" },
    { nepali: "Padhnu", english: "To read / study", german: "Lesen / Studieren", category: "Verbs" },
    { nepali: "Siknu", english: "To learn", german: "Lernen", category: "Verbs" },
    { nepali: "Sikaunu", english: "To teach", german: "Lehren", category: "Verbs" },
    { nepali: "Kinnu", english: "To buy", german: "Kaufen", category: "Verbs" },
    { nepali: "Bechnu", english: "To sell", german: "Verkaufen", category: "Verbs" },
    { nepali: "Dinu", english: "To give", german: "Geben", category: "Verbs" },
    { nepali: "Linu", english: "To take", german: "Nehmen", category: "Verbs" },
    { nepali: "Lyau", english: "To bring", german: "Bringen", category: "Verbs" },
    { nepali: "Rakhnu", english: "To keep / put", german: "Legen / Behalten", category: "Verbs" },
    { nepali: "Phalnu", english: "To throw", german: "Werfen", category: "Verbs" },
    { nepali: "Khaajaa", english: "Snack", german: "Snack", category: "Food" },
    { nepali: "Bhat", english: "Rice (Cooked)", german: "Reis (Gekocht)", category: "Food" },
    { nepali: "Chamal", english: "Rice (Uncooked)", german: "Reis (Ungekocht)", category: "Food" },
    { nepali: "Daal", english: "Lentil soup", german: "Linsensuppe", category: "Food" },
    { nepali: "Tarkari", english: "Vegetable curry", german: "Gemüsecurry", category: "Food" },
    { nepali: "Aalu", english: "Potato", german: "Kartoffel", category: "Food" },
    { nepali: "Pyaaj", english: "Onion", german: "Zwiebel", category: "Food" },
    { nepali: "Golbheda", english: "Tomato", german: "Tomate", category: "Food" },
    { nepali: "Lasun", english: "Garlic", german: "Knoblauch", category: "Food" },
    { nepali: "Aduwa", english: "Ginger", german: "Ingwer", category: "Food" },
    { nepali: "Khursani", english: "Chili", german: "Chili", category: "Food" },
    { nepali: "Nun", english: "Salt", german: "Salz", category: "Food" },
    { nepali: "Chini", english: "Sugar", german: "Zucker", category: "Food" },
    { nepali: "Tel", english: "Oil", german: "Öl", category: "Food" },
    { nepali: "Masu", english: "Meat", german: "Fleisch", category: "Food" },
    { nepali: "Kukhura ko masu", english: "Chicken meat", german: "Hühnerfleisch", category: "Food" },
    { nepali: "Bheda ko masu", english: "Mutton / Sheep meat", german: "Schaffleisch", category: "Food" },
    { nepali: "Bungur ko masu", english: "Pork", german: "Schweinefleisch", category: "Food" },
    { nepali: "Machha", english: "Fish (Food)", german: "Fisch (Essen)", category: "Food" },
    { nepali: "Anda", english: "Egg", german: "Ei", category: "Food" },
    { nepali: "Dudh", english: "Milk", german: "Milch", category: "Food" },
    { nepali: "Dahi", english: "Yogurt", german: "Joghurt", category: "Food" },
    { nepali: "Makkhan", english: "Butter", german: "Butter", category: "Food" },
    { nepali: "Chiya", english: "Tea", german: "Tee", category: "Food" },
    { nepali: "Kafi", english: "Coffee", german: "Kaffee", category: "Food" },
    { nepali: "Roti", english: "Flatbread", german: "Fladenbrot", category: "Food" },
    { nepali: "Phalphul", english: "Fruits", german: "Obst / Früchte", category: "Food" },
    { nepali: "Syau", english: "Apple", german: "Apfel", category: "Food" },
    { nepali: "Kera", english: "Banana", german: "Banane", category: "Food" },
    { nepali: "Suntala", english: "Orange", german: "Orange", category: "Food" },
    { nepali: "Aamp", english: "Mango", german: "Mango", category: "Food" },
    { nepali: "Kagati", english: "Lemon", german: "Zitrone", category: "Food" },
    { nepali: "Angur", english: "Grapes", german: "Trauben", category: "Food" },
    { nepali: "Mitho", english: "Delicious", german: "Lecker", category: "Adjectives" },
    { nepali: "Piro", english: "Spicy", german: "Scharf", category: "Adjectives" },
    { nepali: "Namilo", english: "Not tasty", german: "Nicht lecker", category: "Adjectives" },
    { nepali: "Tato", english: "Hot (temperature)", german: "Heiß", category: "Adjectives" },
    { nepali: "Chiso", english: "Cold (temperature)", german: "Kalt", category: "Adjectives" },
    { nepali: "Garmi", english: "Hot (weather)", german: "Heißes Wetter", category: "Adjectives" },
    { nepali: "Jaado", english: "Cold (weather)", german: "Kaltes Wetter", category: "Adjectives" },
    { nepali: "Ramro", english: "Good / Beautiful", german: "Gut / Schön", category: "Adjectives" },
    { nepali: "Naramro", english: "Bad / Ugly", german: "Schlecht / Hässlich", category: "Adjectives" },
    { nepali: "Thulo", english: "Big", german: "Groß", category: "Adjectives" },
    { nepali: "Sano", english: "Small", german: "Klein", category: "Adjectives" },
    { nepali: "Lamo", english: "Long", german: "Lang", category: "Adjectives" },
    { nepali: "Chhoto", english: "Short (length)", german: "Kurz", category: "Adjectives" },
    { nepali: "Hocho", english: "Short (height)", german: "Klein (Größe)", category: "Adjectives" },
    { nepali: "Agalo", english: "Tall", german: "Groß (Größe)", category: "Adjectives" },
    { nepali: "Naya", english: "New", german: "Neu", category: "Adjectives" },
    { nepali: "Purano", english: "Old (things)", german: "Alt (Dinge)", category: "Adjectives" },
    { nepali: "Budo", english: "Old (person)", german: "Alt (Person)", category: "Adjectives" },
    { nepali: "Tadha", english: "Far", german: "Weit", category: "Adjectives" },
    { nepali: "Najik", english: "Near", german: "Nah", category: "Adjectives" },
    { nepali: "Sajilo", english: "Easy", german: "Einfach", category: "Adjectives" },
    { nepali: "Gaaro", english: "Difficult", german: "Schwierig", category: "Adjectives" },
    { nepali: "Sasto", english: "Cheap", german: "Billig", category: "Adjectives" },
    { nepali: "Mahango", english: "Expensive", german: "Teuer", category: "Adjectives" },
    { nepali: "Safaa", english: "Clean", german: "Sauber", category: "Adjectives" },
    { nepali: "Fohor", english: "Dirty", german: "Schmutzig", category: "Adjectives" },
    { nepali: "Khushi", english: "Happy", german: "Glücklich", category: "Adjectives" },
    { nepali: "Dukhi", english: "Sad", german: "Traurig", category: "Adjectives" },
    { nepali: "Risaeko", english: "Angry", german: "Wütend", category: "Adjectives" },
    { nepali: "Thakeko", english: "Tired", german: "Müde", category: "Adjectives" },
    { nepali: "Bhoklaagyo", english: "Hungry", german: "Hungrig", category: "Adjectives" },
    { nepali: "Tirkha", english: "Thirsty", german: "Durstig", category: "Adjectives" },
    { nepali: "Chhito", english: "Fast", german: "Schnell", category: "Adjectives" },
    { nepali: "Dhilo", english: "Slow / Late", german: "Langsam / Spät", category: "Adjectives" },
    { nepali: "Gahro", english: "Heavy", german: "Schwer (Gewicht)", category: "Adjectives" },
    { nepali: "Haluka", english: "Light (weight)", german: "Leicht", category: "Adjectives" },
    { nepali: "Ma", english: "I", german: "Ich", category: "Pronouns" },
    { nepali: "Timi", english: "You (Informal)", german: "Du", category: "Pronouns" },
    { nepali: "Tapai", english: "You (Formal)", german: "Sie (Höflich)", category: "Pronouns" },
    { nepali: "U / Uha", english: "He / She", german: "Er / Sie", category: "Pronouns" },
    { nepali: "Hami", english: "We", german: "Wir", category: "Pronouns" },
    { nepali: "Unihaaru", english: "They", german: "Sie (Plural)", category: "Pronouns" },
    { nepali: "Mero", english: "My", german: "Mein", category: "Pronouns" },
    { nepali: "Timro", english: "Your (Informal)", german: "Dein", category: "Pronouns" },
    { nepali: "Tapaiko", english: "Your (Formal)", german: "Ihr (Höflich)", category: "Pronouns" },
    { nepali: "Usko", english: "His / Her", german: "Sein / Ihr", category: "Pronouns" },
    { nepali: "Hamro", english: "Our", german: "Unser", category: "Pronouns" },
    { nepali: "Ko?", english: "Who?", german: "Wer?", category: "Questions" },
    { nepali: "Ke?", english: "What?", german: "Was?", category: "Questions" },
    { nepali: "Kaha?", english: "Where?", german: "Wo?", category: "Questions" },
    { nepali: "Kati?", english: "How much / How many?", german: "Wie viel?", category: "Questions" },
    { nepali: "Kaile?", english: "When?", german: "Wann?", category: "Questions" },
    { nepali: "Kina?", english: "Why?", german: "Warum?", category: "Questions" },
    { nepali: "Kasari?", english: "How?", german: "Wie?", category: "Questions" },
    { nepali: "Kasko?", english: "Whose?", german: "Wessen?", category: "Questions" },
    { nepali: "Kun?", english: "Which?", german: "Welche?", category: "Questions" },
    { nepali: "Desh", english: "Country", german: "Land", category: "Places" },
    { nepali: "Shahar", english: "City", german: "Stadt", category: "Places" },
    { nepali: "Gaun", english: "Village", german: "Dorf", category: "Places" },
    { nepali: "Bato", english: "Road / Path", german: "Weg / Straße", category: "Places" },
    { nepali: "Pasal", english: "Shop", german: "Laden / Geschäft", category: "Places" },
    { nepali: "Bajar", english: "Market", german: "Markt", category: "Places" },
    { nepali: "Vidyalaya", english: "School", german: "Schule", category: "Places" },
    { nepali: "Karyalaya", english: "Office", german: "Büro", category: "Places" },
    { nepali: "Aspatal", english: "Hospital", german: "Krankenhaus", category: "Places" },
    { nepali: "Mandir", english: "Temple", german: "Tempel", category: "Places" },
    { nepali: "Nadi", english: "River", german: "Fluss", category: "Nature" },
    { nepali: "Pahad", english: "Hill / Mountain", german: "Hügel / Berg", category: "Nature" },
    { nepali: "Himal", english: "Snowy Mountain", german: "Schneeberg", category: "Nature" },
    { nepali: "Rukh", english: "Tree", german: "Baum", category: "Nature" },
    { nepali: "Phool", english: "Flower", german: "Blume", category: "Nature" },
    { nepali: "Ghaas", english: "Grass", german: "Gras", category: "Nature" },
    { nepali: "Pani", english: "Water / Rain", german: "Wasser / Regen", category: "Nature" },
    { nepali: "Aakash", english: "Sky", german: "Himmel", category: "Nature" },
    { nepali: "Ghaam", english: "Sun", german: "Sonne", category: "Nature" },
    { nepali: "Joon", english: "Moon", german: "Mond", category: "Nature" },
    { nepali: "Taara", english: "Star", german: "Stern", category: "Nature" },
    { nepali: "Dhuwa", english: "Smoke", german: "Rauch", category: "Nature" },
    { nepali: "Mato", english: "Soil / Dirt", german: "Erde / Schmutz", category: "Nature" },
    { nepali: "Dhunga", english: "Stone", german: "Stein", category: "Nature" },
    { nepali: "Gaadi", english: "Car / Vehicle", german: "Auto / Fahrzeug", category: "Transport" },
    { nepali: "Bus", english: "Bus", german: "Bus", category: "Transport" },
    { nepali: "Hawaijahaj", english: "Airplane", german: "Flugzeug", category: "Transport" },
    { nepali: "Rail", english: "Train", german: "Zug", category: "Transport" },
    { nepali: "Dunga", english: "Boat", german: "Boot", category: "Transport" },
    { nepali: "Bicycle", english: "Bicycle", german: "Fahrrad", category: "Transport" },
    { nepali: "Bhada", english: "Fare / Rent", german: "Fahrpreis / Miete", category: "Transport" },
    { nepali: "Ticket", english: "Ticket", german: "Ticket", category: "Transport" },
    { nepali: "Driver", english: "Driver", german: "Fahrer", category: "Transport" },
    { nepali: "Mathi", english: "Up / Above", german: "Oben", category: "Directions" },
    { nepali: "Tala", english: "Down / Below", german: "Unten", category: "Directions" },
    { nepali: "Daya", english: "Right", german: "Rechts", category: "Directions" },
    { nepali: "Baya", english: "Left", german: "Links", category: "Directions" },
    { nepali: "Agaadi", english: "Front / Ahead", german: "Vorne / Voraus", category: "Directions" },
    { nepali: "Pachhaadi", english: "Behind / Back", german: "Hinten / Zurück", category: "Directions" },
    { nepali: "Bhitra", english: "Inside", german: "Drinnen", category: "Directions" },
    { nepali: "Bahira", english: "Outside", german: "Draußen", category: "Directions" },
    { nepali: "Sidha", english: "Straight", german: "Geradeaus", category: "Directions" },
    { nepali: "Ek saya", english: "One hundred", german: "Einhundert", category: "Numbers" },
    { nepali: "Dui saya", english: "Two hundred", german: "Zweihundert", category: "Numbers" },
    { nepali: "Ek hazaar", english: "One thousand", german: "Eintausend", category: "Numbers" },
    { nepali: "Bees", english: "Twenty", german: "Zwanzig", category: "Numbers" },
    { nepali: "Tees", english: "Thirty", german: "Dreißig", category: "Numbers" },
    { nepali: "Chalis", english: "Forty", german: "Vierzig", category: "Numbers" },
    { nepali: "Pachas", english: "Fifty", german: "Fünfzig", category: "Numbers" },
    { nepali: "Sathi", english: "Sixty", german: "Sechzig", category: "Numbers" },
    { nepali: "Sattari", english: "Seventy", german: "Siebzig", category: "Numbers" },
    { nepali: "Asi", english: "Eighty", german: "Achtzig", category: "Numbers" },
    { nepali: "Nabbe", english: "Ninety", german: "Neunzig", category: "Numbers" },
    { nepali: "Pheri bhaetaula", english: "See you again", german: "Auf Wiedersehen", category: "Phrases" },
    { nepali: "Ramro sanga janu", english: "Have a safe trip", german: "Gute Reise", category: "Phrases" },
    { nepali: "Maafi pau", english: "Forgive me", german: "Vergib mir", category: "Phrases" },
    { nepali: "Kripaya malai sahayog garnuhos", english: "Please help me", german: "Bitte helfen Sie mir", category: "Phrases" },
    { nepali: "Malai thaha chhaina", english: "I don't know", german: "Ich weiß nicht", category: "Phrases" },
    { nepali: "Ke bhayo?", english: "What happened?", german: "Was ist passiert?", category: "Phrases" },
    { nepali: "Maile bujhina", english: "I didn't understand", german: "Ich habe es nicht verstanden", category: "Phrases" },
    { nepali: "Bistarai bhannuhos", english: "Please speak slowly", german: "Bitte sprechen Sie langsam", category: "Phrases" },
    { nepali: "Ma thakeko chhu", english: "I am tired", german: "Ich bin müde", category: "Phrases" }
,
    { nepali: "Kholnu", english: "To open", german: "Öffnen", category: "Verbs" },
    { nepali: "Banda garnu", english: "To close", german: "Schließen", category: "Verbs" },
    { nepali: "Basnu", english: "To sit", german: "Sitzen", category: "Verbs" },
    { nepali: "Ubheko", english: "To stand", german: "Stehen", category: "Verbs" },
    { nepali: "Gaaunu", english: "To sing", german: "Singen", category: "Verbs" },
    { nepali: "Nachnu", english: "To dance", german: "Tanzen", category: "Verbs" },
    { nepali: "Khelne", english: "To play", german: "Spielen", category: "Verbs" },
    { nepali: "Kaam garnu", english: "To work", german: "Arbeiten", category: "Verbs" },
    { nepali: "Pakaunu", english: "To cook", german: "Kochen", category: "Verbs" },
    { nepali: "Dhunnu", english: "To wash", german: "Waschen", category: "Verbs" },
    { nepali: "Nuhaunu", english: "To bathe", german: "Baden", category: "Verbs" },
    { nepali: "Paucha laaunu", english: "To wipe", german: "Wischen", category: "Verbs" },
    { nepali: "Nidaunu", english: "To fall asleep", german: "Einschlafen", category: "Verbs" },
    { nepali: "Sapana dekhnu", english: "To dream", german: "Träumen", category: "Verbs" },
    { nepali: "Hansnu", english: "To laugh", german: "Lachen", category: "Verbs" },
    { nepali: "Runu", english: "To cry", german: "Weinen", category: "Verbs" },
    { nepali: "Muskuraunu", english: "To smile", german: "Lächeln", category: "Verbs" },
    { nepali: "Risau nu", english: "To get angry", german: "Wütend werden", category: "Verbs" },
    { nepali: "Daraunu", english: "To be scared", german: "Sich fürchten", category: "Verbs" },
    { nepali: "Pukarnu", english: "To call out", german: "Rufen", category: "Verbs" },
    { nepali: "Bhetnu", english: "To meet", german: "Treffen", category: "Verbs" },
    { nepali: "Chhunu", english: "To touch", german: "Berühren", category: "Verbs" },
    { nepali: "Samjhanu", english: "To remember", german: "Sich erinnern", category: "Verbs" },
    { nepali: "Birsanu", english: "To forget", german: "Vergessen", category: "Verbs" },
    { nepali: "Udaunu", english: "To fly", german: "Fliegen", category: "Verbs" },
    { nepali: "Kudnu", english: "To jump", german: "Springen", category: "Verbs" },
    { nepali: "Bilaunu", english: "To melt", german: "Schmelzen", category: "Verbs" },
    { nepali: "Jamnu", english: "To freeze", german: "Frieren", category: "Verbs" },
    { nepali: "Umalnu", english: "To boil", german: "Kochen (Flüssigkeit)", category: "Verbs" },
    { nepali: "Chakhnu", english: "To taste", german: "Schmecken", category: "Verbs" },
    { nepali: "Sunghnu", english: "To smell", german: "Riechen", category: "Verbs" },
    { nepali: "KaaTnu", english: "To cut", german: "Schneiden", category: "Verbs" },
    { nepali: "Jodnu", english: "To join / connect", german: "Verbinden", category: "Verbs" },
    { nepali: "ToDnu", english: "To break", german: "Brechen", category: "Verbs" },
    { nepali: "Banaunu", english: "To make / build", german: "Machen / Bauen", category: "Verbs" },
    { nepali: "Bhathkaunu", english: "To destroy", german: "Zerstören", category: "Verbs" },
    { nepali: "Jalnu", english: "To burn", german: "Brennen", category: "Verbs" },
    { nepali: "Marnu", english: "To die", german: "Sterben", category: "Verbs" },
    { nepali: "Bachnu", english: "To live / survive", german: "Leben / Überleben", category: "Verbs" },
    { nepali: "Khojnu", english: "To search", german: "Suchen", category: "Verbs" },
    { nepali: "Paaunu", english: "To find / receive", german: "Finden / Bekommen", category: "Verbs" },
    { nepali: "Harau nu", english: "To lose", german: "Verlieren", category: "Verbs" },
    { nepali: "Jitnu", english: "To win", german: "Gewinnen", category: "Verbs" },
    { nepali: "Haarnu", english: "To lose (a game)", german: "Verlieren (Spiel)", category: "Verbs" },
    { nepali: "Phalnu", english: "To bear fruit", german: "Früchte tragen", category: "Verbs" },
    { nepali: "Bikash garnu", english: "To develop", german: "Entwickeln", category: "Verbs" },
    { nepali: "Asha garnu", english: "To hope", german: "Hoffen", category: "Verbs" },
    { nepali: "Biswas garnu", english: "To believe / trust", german: "Glauben / Vertrauen", category: "Verbs" },
    { nepali: "Maya garnu", english: "To love", german: "Lieben", category: "Verbs" },
    { nepali: "Ghrina garnu", english: "To hate", german: "Hassen", category: "Verbs" },
    { nepali: "Khusi banaunu", english: "To make happy", german: "Glücklich machen", category: "Verbs" },
    { nepali: "Dukha dinu", english: "To give pain / hurt", german: "Schmerzen bereiten", category: "Verbs" },
    { nepali: "Binti garnu", english: "To request / beg", german: "Bitten", category: "Verbs" },
    { nepali: "Ashirbad dinu", english: "To bless", german: "Segnen", category: "Verbs" },
    { nepali: "Bela", english: "Season / Period", german: "Jahreszeit / Periode", category: "Nature" },
    { nepali: "Basanta", english: "Spring (Season)", german: "Frühling", category: "Nature" },
    { nepali: "Grishma", english: "Summer (Season)", german: "Sommer", category: "Nature" },
    { nepali: "Sharad", english: "Autumn (Season)", german: "Herbst", category: "Nature" },
    { nepali: "Hiunda", english: "Winter (Season)", german: "Winter", category: "Nature" },
    { nepali: "Barsha", english: "Rainy Season", german: "Regenzeit", category: "Nature" },
    { nepali: "Jhari", english: "Continuous Rain", german: "Dauerregen", category: "Nature" },
    { nepali: "Kuhira", english: "Fog", german: "Nebel", category: "Nature" },
    { nepali: "Hiun", english: "Snow", german: "Schnee", category: "Nature" },
    { nepali: "Tufan", english: "Storm", german: "Sturm", category: "Nature" },
    { nepali: "Bhui-chalo", english: "Earthquake", german: "Erdbeben", category: "Nature" },
    { nepali: "Aaglagi", english: "Fire (disaster)", german: "Brand", category: "Nature" },
    { nepali: "Baadhi", english: "Flood", german: "Überschwemmung", category: "Nature" },
    { nepali: "Pahiro", english: "Landslide", german: "Erdrutsch", category: "Nature" },
    { nepali: "Samundra", english: "Ocean / Sea", german: "Ozean / Meer", category: "Nature" },
    { nepali: "Taal", english: "Lake", german: "See", category: "Nature" },
    { nepali: "Pokhari", english: "Pond", german: "Teich", category: "Nature" },
    { nepali: "Bagar", english: "Riverbank", german: "Flussufer", category: "Nature" },
    { nepali: "Kinar", english: "Edge / Bank", german: "Rand / Ufer", category: "Nature" },
    { nepali: "Dhulo", english: "Dust", german: "Staub", category: "Nature" },
    { nepali: "Hawa", english: "Wind / Air", german: "Wind / Luft", category: "Nature" },
    { nepali: "Ujyalo", english: "Bright / Light", german: "Hell / Licht", category: "Adjectives" },
    { nepali: "Adhyaro", english: "Dark", german: "Dunkel", category: "Adjectives" },
    { nepali: "Bakhlo", english: "Thick", german: "Dick (Material)", category: "Adjectives" },
    { nepali: "Patalo", english: "Thin", german: "Dünn", category: "Adjectives" },
    { nepali: "Moto", english: "Fat", german: "Fett / Dick (Person)", category: "Adjectives" },
    { nepali: "Dublo", english: "Skinny / Lean", german: "Dünn / Schlank", category: "Adjectives" },
    { nepali: "Gilo", english: "Soft (wet)", german: "Weich (feucht)", category: "Adjectives" },
    { nepali: "Sukha", english: "Dry", german: "Trocken", category: "Adjectives" },
    { nepali: "Chillo", english: "Smooth / Oily", german: "Glatt / Ölig", category: "Adjectives" },
    { nepali: "Khasro", english: "Rough", german: "Rau", category: "Adjectives" },
    { nepali: "Goda", english: "Leg / Foot (respectful)", german: "Bein / Fuß (höflich)", category: "Body Parts" },
    { nepali: "Pithyu", english: "Back (Body)", german: "Rücken", category: "Body Parts" },
    { nepali: "Kandh", english: "Shoulder", german: "Schulter", category: "Body Parts" },
    { nepali: "Gunda", english: "Knee", german: "Knie", category: "Body Parts" },
    { nepali: "Lingo", english: "Gender / Pole", german: "Geschlecht / Pfahl", category: "Body Parts" },
    { nepali: "Gidi", english: "Brain", german: "Gehirn", category: "Body Parts" },
    { nepali: "Nara", english: "Vein", german: "Ader", category: "Body Parts" },
    { nepali: "Haddi", english: "Bone", german: "Knochen", category: "Body Parts" },
    { nepali: "Chhala", english: "Skin", german: "Haut", category: "Body Parts" },
    { nepali: "Maspeshi", english: "Muscle", german: "Muskel", category: "Body Parts" },
    { nepali: "Pwal", english: "Hole", german: "Loch", category: "Misc" },
    { nepali: "Dorii", english: "Rope", german: "Seil", category: "Misc" },
    { nepali: "Baakas", english: "Box", german: "Kiste / Box", category: "Misc" },
    { nepali: "Jhola", english: "Bag", german: "Tasche", category: "Misc" },
    { nepali: "Chabi", english: "Key", german: "Schlüssel", category: "Misc" },
    { nepali: "Taalcha", english: "Lock", german: "Schloss", category: "Misc" },
    { nepali: "Paisa", english: "Money", german: "Geld", category: "Misc" },
    { nepali: "Sun", english: "Gold", german: "Gold", category: "Misc" },
    { nepali: "Chandi", english: "Silver", german: "Silber", category: "Misc" },
    { nepali: "Falam", english: "Iron", german: "Eisen", category: "Misc" },
    { nepali: "Taama", english: "Copper", german: "Kupfer", category: "Misc" },
    { nepali: "Sisa", english: "Glass / Lead", german: "Glas / Blei", category: "Misc" },
    { nepali: "Kagaj", english: "Paper", german: "Papier", category: "Misc" },
    { nepali: "Kalam", english: "Pen", german: "Stift", category: "Misc" },
    { nepali: "Kitab", english: "Book", german: "Buch", category: "Misc" },
    { nepali: "Katha", english: "Story", german: "Geschichte", category: "Misc" },
    { nepali: "Geet", english: "Song", german: "Lied", category: "Misc" },
    { nepali: "Nritaya", english: "Dance (Noun)", german: "Tanz", category: "Misc" },
    { nepali: "Khel", english: "Game", german: "Spiel", category: "Misc" },
    { nepali: "Sikshya", english: "Education", german: "Bildung", category: "Misc" },
    { nepali: "Gyann", english: "Knowledge", german: "Wissen", category: "Misc" },
    { nepali: "Buddhi", english: "Wisdom / Intellect", german: "Weisheit / Intellekt", category: "Misc" },
    { nepali: "Dharma", english: "Religion / Duty", german: "Religion / Pflicht", category: "Misc" },
    { nepali: "Paap", english: "Sin", german: "Sünde", category: "Misc" },
    { nepali: "Punya", english: "Virtue", german: "Tugend", category: "Misc" },
    { nepali: "Pavitra", english: "Holy", german: "Heilig", category: "Adjectives" },
    { nepali: "Asli", english: "Real / Genuine", german: "Echt / Original", category: "Adjectives" },
    { nepali: "Nakkali", english: "Fake", german: "Fälschung", category: "Adjectives" },
    { nepali: "Sacho", english: "True", german: "Wahr", category: "Adjectives" },
    { nepali: "Jhutho", english: "False / Lie", german: "Falsch / Lüge", category: "Adjectives" },
    { nepali: "Ek saya ek", english: "One hundred and one", german: "Hunderteins", category: "Numbers" },
    { nepali: "Dui hazaar", english: "Two thousand", german: "Zweitausend", category: "Numbers" }
];

window.vocabularyList = vocabularyList;